title: OSU IGVC Wiki
description: Documentation on OSU IGVC autonomous vehicle efforts
theme: just-the-docs

url: https://osu-igvc.github.io/

aux_links:
  Wiki Repository: https://github.com/osu-igvc/osu-igvc-docs
aux_links_new_tab: false
